#ifndef _VERSION_H_
#define _VERSION_H_


#define xSTR(text)      #text
#define STR(text)       xSTR(text)


#define MAJOR_VERSION 2
#define MINOR_VERSION 8
#define MAINT_VERSION 2

#define VERSION_NUMBER              MAJOR_VERSION.MINOR_VERSION.MAINT_VERSION
#define BASE_VERSION_NUMBER         MAJOR_VERSION.MINOR_VERSION.MAINT_VERSION
#define VC_BASE_VERSION_NUMBER      MAJOR_VERSION,MINOR_VERSION,MAINT_VERSION,0
#define BASE_VERSION_NUMBER_STR     STR(VERSION_NUMBER)
#define VERSION_NUMBER_STR          "v" BASE_VERSION_NUMBER_STR


#endif // _VERSION_H_
